#!/usr/bin/env python3
"""Generate PR candidates and PR body markdown from evidence diffs.

This script intentionally does not call GitHub by default. The workflow uses
peter-evans/create-pull-request to open a reviewable PR from generated files.
"""
from __future__ import annotations
import argparse, json
from pathlib import Path
from typing import Any, Dict, List
ROOT = Path(__file__).resolve().parents[1]

def load(path: str, default: Any) -> Any:
    p = ROOT / path
    return json.loads(p.read_text(encoding='utf-8')) if p.exists() else default

def candidate_from_diff(d: Dict[str,Any]) -> Dict[str,Any]:
    proposed = d.get('after', {}).get('proposed_evidence', {})
    return {
        'id': f"pr-{d.get('id')}",
        'tool_id': d.get('tool_id'),
        'update_id': d.get('update_id'),
        'title': f"Review evidence update for {d.get('tool_id')}",
        'source_url': d.get('source_url'),
        'proposed_changes': {
            'evidence_added': proposed,
            'asi_depth_review': d.get('after', {}).get('proposed_asi_depth_change', {}),
            'benchmark_recommendations': d.get('after', {}).get('recommended_benchmarks', [])
        },
        'status': 'ready_for_human_review',
        'review_checklist': d.get('review_checklist', [])
    }

def render_markdown(cands: List[Dict[str,Any]]) -> str:
    lines = ['# Auto Update Review PR', '', 'This PR was generated by the Agentic AI Security update-review pipeline. It proposes reviewable evidence changes only; maintainers should verify claims before merging.', '']
    if not cands:
        lines += ['No PR candidates were generated.']
        return '\n'.join(lines)
    for c in cands:
        ev = c.get('proposed_changes', {}).get('evidence_added', {})
        lines += [
            f"## {c.get('title')}",
            f"- Tool: `{c.get('tool_id')}`",
            f"- Update ID: `{c.get('update_id')}`",
            f"- Source: {c.get('source_url') or 'not provided'}",
            f"- Proposed claim: {ev.get('claim','')}",
            f"- Supports: {', '.join(ev.get('supports', []) or [])}",
            f"- Recommended benchmarks: {', '.join(c.get('proposed_changes', {}).get('benchmark_recommendations', []) or [])}",
            '',
            '### Human Review Checklist',
        ]
        for item in c.get('review_checklist', []): lines.append(f"- [ ] {item}")
        lines.append('')
    return '\n'.join(lines)

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--diffs', default='data/updates/evidence_diffs.json')
    ap.add_argument('--output', default='data/updates/pr_candidates.json')
    ap.add_argument('--markdown-output', default='outputs/pr_candidate_sample.md')
    args = ap.parse_args()
    diffs = load(args.diffs, {'diffs': []}).get('diffs', [])
    candidates = [candidate_from_diff(d) for d in diffs if d.get('status') == 'pending_review']
    out = {'meta': {'version':'v1.1','generated_by':'agents/pr_generator.py','count':len(candidates)}, 'candidates': candidates}
    p = ROOT / args.output; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding='utf-8')
    md = render_markdown(candidates)
    mp = ROOT / args.markdown_output; mp.parent.mkdir(parents=True, exist_ok=True); mp.write_text(md, encoding='utf-8')
    print(f"Wrote {len(candidates)} PR candidates to {p} and {mp}")
if __name__ == '__main__': main()
